# Gradle Arguments
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1
minecraft_version_range=[26.1,]
neo_version=26.1.0.1-beta

## Mod Properties
mod_id=scalarutils_integration
mod_name=Scalar Utils 6 Integration
mod_license=GNU General Public License v3 (GPLv3)
mod_version=26.1-6.1.0.1
mod_group_id=site.scalarstudios.scalarutils_integration