# License
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="scalarutils6_integration.png"
authors="Lemon_Juiced, TechDahTurtle"
description='''
The Revival of Scalar Utils for Minecraft 26.1+'s Integration Module
'''

# Dependencies
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="scalar_core"
    type="required"
    versionRange="=[26.1-1.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="scalarutils"
    type="required"
    versionRange="=[26.1-6.1.0.5,)"
    ordering="NONE"
    side="BOTH"